# Generated by Django 5.2.4 on 2025-07-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
